#!/bin/bash
# fix_push.sh — 一键修复 GitHub 大文件推送失败问题
# 适用于 inkGrid 项目：自动忽略并移除 >30MB 文件

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${GREEN}🔧 开始修复大文件推送问题...${NC}"

# 1. 确保 .gitignore 存在且包含关键规则
if [ ! -f ".gitignore" ]; then
  echo "# Generated by fix_push.sh" > .gitignore
fi

# 添加忽略规则（去重）
{
  echo ""
  echo "# Ignore large directories (auto-added)"
  echo "processor/venv/"
  echo "backend/models/"
} >> .gitignore

# 去重（保留最后一 occurrence）
awk '!seen[$0]++' .gitignore > .gitignore.tmp && mv .gitignore.tmp .gitignore

echo -e "${GREEN}✅ 已更新 .gitignore${NC}"

# 2. 查找并移除 >30MB 的已跟踪文件
THRESHOLD=31457280  # 30 * 1024 * 1024
TO_REMOVE=()

while IFS= read -r file; do
  if [ -f "$file" ] && [ "$(stat -f %z "$file" 2>/dev/null)" -gt "$THRESHOLD" ] 2>/dev/null; then
    TO_REMOVE+=("$file")
    size_mb=$(($(stat -f %z "$file") / 1024 / 1024))
    echo "  🗑️  将移除: $file (${size_mb} MB)"
  fi
done < <(git ls-files 2>/dev/null || echo "")

# 显式添加已知大文件（防漏）
KNOWN_LARGE=(
  "processor/venv/lib/python3.12/site-packages/paddle/base/libpaddle.so"
  "processor/venv/lib/python3.12/site-packages/paddle/libs/libphi_core.dylib"
  "backend/models/sam_vit_b_01ec64.pth"
)

for f in "${KNOWN_LARGE[@]}"; do
  if [ -f "$f" ] && [ "$(stat -f %z "$f" 2>/dev/null)" -gt "$THRESHOLD" ] 2>/dev/null; then
    if [[ ! " ${TO_REMOVE[@]} " =~ " ${f} " ]]; then
      TO_REMOVE+=("$f")
      size_mb=$(($(stat -f %z "$f") / 1024 / 1024))
      echo "  🗑️  补充移除: $f (${size_mb} MB)"
    fi
  fi
done

if [ ${#TO_REMOVE[@]} -eq 0 ]; then
  echo -e "${GREEN}✅ 未发现 >30MB 的已跟踪文件${NC}"
else
  echo "Removing ${#TO_REMOVE[@]} large files from Git index..."
  git rm -r --cached "${TO_REMOVE[@]}" 2>/dev/null || true
  echo -e "${GREEN}✅ 已从 Git 索引中移除 ${#TO_REMOVE[@]} 个大文件${NC}"
fi

# 3. 提交更改
git add .gitignore
git status --short | grep -q '^M' && {
  git commit -m "chore: ignore and untrack files >30MB (fix GH001)" || {
    echo -e "${RED}❌ 提交失败，请检查是否有冲突${NC}"
    exit 1
  }
} || echo "⚠️ 无变更需提交"

echo -e "\n${GREEN}🎉 修复完成！现在可安全推送：${NC}"
echo "   git push origin main"