#!/bin/bash
# 颜勤礼碑资源获取脚本
# 使用前请确保已安装 wget 或 curl

set -e

echo "=========================================="
echo "  颜勤礼碑资源获取脚本"
echo "=========================================="

# 创建目录
STELE_DIR="steles/3-kaishu/2-yanqinli"
OUTPUT_DIR="test_output/颜勤礼碑"
mkdir -p "$STELE_DIR"
mkdir -p "$OUTPUT_DIR"

echo ""
echo "📁 目录结构已创建:"
echo "  $STELE_DIR - 存储原碑图片"
echo "  $OUTPUT_DIR - 存储处理后图片"

echo ""
echo "=========================================="
echo "  资源下载链接"
echo "=========================================="
echo ""
echo "【主要资源】书格网 - 北京故宫博物院藏本"
echo "  链接: https://old.shuge.org/ebook/yan-qinli-bei/"
echo "  格式: PDF高清 (169MB) + JPG拓片"
echo "  内容: 民国时期拓本，碑阳、碑阴、碑侧完整"
echo ""
echo "【备用资源】"
echo "  1. 书法字典网: http://www.shufazidian.com/ziliao_m/4388.html"
echo "  2. 360doc单字图: http://www.360doc.com/content/23/0814/13/11677680_1092465333.shtml"
echo ""
echo "【高清单字资源】"
echo "  书法空间: http://www.9610.com/yanlib/"
echo "  提供颜勤礼碑单字高清图"
echo ""

echo "=========================================="
echo "  手动下载步骤"
echo "=========================================="
echo ""
echo "1. 访问书格网链接:"
echo "   https://old.shuge.org/ebook/yan-qinli-bei/"
echo ""
echo "2. 下载以下文件到 $STELE_DIR 目录:"
echo "   - 颜勤礼碑整拓图 (JPG格式)"
echo "   - 或下载PDF后用工具转换为JPG"
echo ""
echo "3. 建议文件名:"
echo "   yanqinli_full.jpg - 整碑拓片"
echo "   yanqinli_yang.jpg - 碑阳"
echo "   yanqinli_yin.jpg  - 碑阴"
echo "   yanqinli_ce.jpg   - 碑侧"
echo ""

echo "=========================================="
echo "  自动处理流程 (下载后执行)"
echo "=========================================="
echo ""
echo "下载完成后，运行以下命令处理图片:"
echo "  cd processor && python3 process_stele.py --stele 颜勤礼碑 --input ../$STELE_DIR/yanqinli_full.jpg"
echo ""
echo "或使用系统API上传处理:"
echo "  curl -X POST http://localhost:8000/api/grid/detect \\"
echo "    -F file=@$STELE_DIR/yanqinli_full.jpg \\"
echo "    -F expected_chars=1667"
echo ""

echo "=========================================="
echo "  数据结构说明"
echo "=========================================="
echo ""
echo "处理完成后将生成:"
echo "  1. 单字图片: test_output/颜勤礼碑/颜勤礼碑_char_*.jpg (~1667张)"
echo "  2. 元数据:   test_output/颜勤礼碑/result.json"
echo "  3. 可视化:   test_output/颜勤礼碑/visualization.jpg"
echo ""

echo "✅ 准备就绪，请按上述步骤下载图片资源"
